# Generated by Django 4.2.6 on 2023-10-15 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='img_produto')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('SUPERIOR', 'Parte Superior'), ('INFERIOR', 'Parte Inferior'), ('UNICA', 'Peça Única'), ('TER_PECA', 'Terceira Peça'), ('ACESSORIOS', 'Acessórios'), ('CALÇADO', 'Calçado'), ('OUTROS', 'Outros')], max_length=15)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
