# Generated by Django 4.2.6 on 2023-10-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
