# Generated by Django 4.2.6 on 2023-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('SUPERIOR', 'Parte Superior'), ('INFERIOR', 'Parte Inferior'), ('UNICA', 'Peça Única'), ('TER_PECA', 'Terceira Peça'), ('ACESSORIOS', 'Acessórios'), ('CALÇADO', 'Calçado'), ('OUTROS', 'Outros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(choices=[('CAMISETA', 'Camiseta'), ('REGATA', 'Regata'), ('CROPPED', 'Cropped'), ('CAMISA', 'Camisa'), ('SHORTS', 'Shorts'), ('SAIA', 'Saia'), ('CALCA', 'Calça')], max_length=100),
        ),
    ]
