# Generated by Django 4.2.6 on 2023-10-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_produto_categoria_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='subcategoria',
        ),
    ]
